Traceback (most recent call last):
  File "/Users/feilong/miniconda3/envs/py/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/feilong/miniconda3/envs/py/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/feilong/miniconda3/envs/py/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/feilong/miniconda3/envs/py/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/feilong/miniconda3/envs/py/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/feilong/miniconda3/envs/py/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/feilong/miniconda3/envs/py/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/feilong/miniconda3/envs/py/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
colors = np.array(sns.color_palette('tab10'))
np.set_printoptions(4, linewidth=200)
if os.path.exists('Arial.ttf'):
    from matplotlib import font_manager
    font_manager.fontManager.addfont('Arial.ttf')
mpl.rcParams['font.family'] = 'Arial'
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[3], line 3[0m
[1;32m      1[0m colors [38;5;241m=[39m np[38;5;241m.[39marray(sns[38;5;241m.[39mcolor_palette([38;5;124m'[39m[38;5;124mtab10[39m[38;5;124m'[39m))
[1;32m      2[0m np[38;5;241m.[39mset_printoptions([38;5;241m4[39m, linewidth[38;5;241m=[39m[38;5;241m200[39m)
[0;32m----> 3[0m [38;5;28;01mif[39;00m [43mos[49m[38;5;241m.[39mpath[38;5;241m.[39mexists([38;5;124m'[39m[38;5;124mArial.ttf[39m[38;5;124m'[39m):
[1;32m      4[0m     [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m [38;5;28;01mimport[39;00m font_manager
[1;32m      5[0m     font_manager[38;5;241m.[39mfontManager[38;5;241m.[39maddfont([38;5;124m'[39m[38;5;124mArial.ttf[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'os' is not defined
NameError: name 'os' is not defined

